In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [285]:
import pandas as pd

url = '/content/drive/MyDrive/Nasa Hackathon/Water Quality Dataset/lab_results.csv'

df=pd.read_csv(url)

In [286]:
df.head()

,station_id,station_name,full_station_name,station_number,station_type,latitude,longitude,status,county_name,sample_code,sample_date,sample_depth,sample_depth_units,parameter,result,reporting_limit,units,method_name
0,8135,01S04E32C001M,01S04E32C001M,01S04E32C001M,Groundwater,37.8073,-121.5617,"Public, Review Status Unknown",Alameda,WDIS_0719152,05/03/1967 09:00,NaN,Feet,Conductance,3480,1.0,uS/cm,EPA 120.1
1,8135,01S04E32C001M,01S04E32C001M,01S04E32C001M,Groundwater,37.8073,-121.5617,"Public, Review Status Unknown",Alameda,WDIS_0719152,05/03/1967 09:00,NaN,Feet,Dissolved Boron,7.7,0.1,mg/L,"Std Method 4500-B, C"
2,8135,01S04E32C001M,01S04E32C001M,01S04E32C001M,Groundwater,37.8073,-121.5617,"Public, Review Status Unknown",Alameda,WDIS_0719152,05/03/1967 09:00,NaN,Feet,Dissolved Calcium,68,1.0,mg/L,EPA 215.2
3,8135,01S04E32C001M,01S04E32C001M,01S04E32C001M,Groundwater,37.8073,-121.5617,"Public, Review Status Unknown",Alameda,WDIS_0719152,05/03/1967 09:00,NaN,Feet,Dissolved Chloride,758,0.1,mg/L,"Std Method 4500-Cl, B"
4,8135,01S04E32C001M,01S04E32C001M,01S04E32C001M,Groundwater,37.8073,-121.5617,"Public, Review Status Unknown",Alameda,WDIS_0719152,05/03/1967 09:00,NaN,Feet,Dissolved Magnesium,59,0.1,mg/L,"Std Method 3500-Mg, E"

In [287]:
print(df.info(show_counts=True))
print("=======================================================")
print("Shape", df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601420 entries, 0 to 4601419
Data columns (total 18 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   station_id          4601420 non-null  int64
 1   station_name        4601420 non-null  object
 2   full_station_name   4601420 non-null  object
 3   station_number      4601420 non-null  object
 4   station_type        4601420 non-null  object
 5   latitude            4463337 non-null  float64
 6   longitude           4463337 non-null  float64
 7   status              4601420 non-null  object
 8   county_name         4601420 non-null  object
 9   sample_code         4601420 non-null  object
 10  sample_date         4601420 non-null  object
 11  sample_depth        1819260 non-null  float64
 12  sample_depth_units  4601420 non-null  object
 13  parameter           4601420 non-null  object
 14  result              4560451 non-null  object
 15  reporting_limit     4583955 non-null  float64
 16  units               4601420 non-null  object
 17  method_name         4601420 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 631.9+ MB
None
=======================================================
Shape (4601420, 18)

In [288]:
df = df.drop(columns=['station_id','station_name','full_station_name','station_number','status','sample_code','sample_date','sample_depth','sample_depth_units','reporting_limit','method_name'])

In [289]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601420 entries, 0 to 4601419
Data columns (total 7 columns):
 #   Column        Dtype
---  ------        -----
 0   station_type  object
 1   latitude      float64
 2   longitude     float64
 3   county_name   object
 4   parameter     object
 5   result        object
 6   units         object
dtypes: float64(2), object(5)
memory usage: 245.7+ MB

In [290]:
null_count = df.isnull().sum()
print(null_count)

station_type         0
latitude        138083
longitude       138083
county_name          0
parameter            0
result           40969
units                0
dtype: int64

In [291]:
df = df[df['result'].notna()]

In [292]:
df = df[df['latitude'].notna()]

In [293]:
null_count = df.isnull().sum()
print(null_count)
print(df.shape)

station_type    0
latitude        0
longitude       0
county_name     0
parameter       0
result          0
units           0
dtype: int64
(4428942, 7)

In [294]:
df['parameter'].unique()

array(['Conductance', 'Dissolved Boron', 'Dissolved Calcium',
       'Dissolved Chloride', 'Dissolved Magnesium', 'Dissolved Sodium',
       'Total Alkalinity', 'Total Hardness', 'pH', 'Dissolved Hardness',
       'Dissolved Potassium', 'Dissolved Sulfate',
       'Total Dissolved Solids', 'Dissolved Nitrate',
       'Dissolved Fluoride', 'Total Copper', 'Total Iron',
       'Total Manganese', 'Total Zinc', 'Total Arsenic', 'Total Lead',
       'Dissolved Silica (SiO2)', 'Total Chromium', 'Total Lithium',
       'Total Strontium', 'Total Barium', 'Total Cadmium',
       'Total Chromium, hexavalent (Cr6+)', 'Total Mercury',
       'Total Selenium', 'Total Silver', 'Color', 'Dissolved Iodide',
       'Methylene Blue Active Substances (MBAS)', 'Threshold Odor',
       'Turbidity', '5-Day Biochemical Oxygen Demand',
       'Dissolved Nitrite', 'Dissolved Phosphorus',
       'Dissolved ortho-Phosphate', 'Total Ammonia',
       'Total Kjeldahl Nitrogen', 'Total Organic Nitrogen',
       'Oil and Grease', 'Dissolved Iron', 'Suspended Solids',
       'Volatile Suspended Solids', 'Bromodichloromethane', 'Bromoform',
       'Chloroform', 'Dibromochloromethane', 'Dissolved Bromide',
       'Dissolved Organic Carbon', 'UV Absorbance @254nm',
       'Dissolved Selenium', 'Dissolved Arsenic', 'Dissolved Aluminum',
       'Dissolved Ammonia', 'Dissolved Antimony', 'Dissolved Barium',
       'Dissolved Beryllium', 'Dissolved Cadmium', 'Dissolved Chromium',
       'Dissolved Copper', 'Dissolved Lead', 'Dissolved Manganese',
       'Dissolved Mercury', 'Dissolved Nickel',
       'Dissolved Nitrate + Nitrite', 'Dissolved Silver',
       'Dissolved Zinc', 'Specific Conductance', 'Total Phosphorus',
       'Dissolved Molybdenum', 'Total Aluminum', 'Total Antimony',
       'Total Beryllium', 'Total Nickel', 'Total Organic Carbon',
       'Total Suspended Solids', '1,1,1,2-Tetrachloroethane',
       '1,1,1-Trichloroethane', '1,1,2,2-Tetrachloroethane',
       '1,1,2-Trichloroethane', '1,1-Dichloroethane',
       '1,1-Dichloroethene', '1,1-Dichloropropene',
       '1,2,3-Trichlorobenzene', '1,2,3-Trichloropropane',
       '1,2,4-Trichlorobenzene', '1,2,4-Trimethylbenzene',
       '1,2-Dibromo-3-chloropropane (DBCP)', '1,2-Dibromoethane (EDB)',
       '1,2-Dichlorobenzene', '1,2-Dichloroethane', '1,2-Dichloropropane',
       '1,3,5-Trimethylbenzene', '1,3-Dichlorobenzene',
       '1,3-Dichloropropane', '1,4-Dichlorobenzene',
       '2,2-Dichloropropane', '2-Chlorotoluene', '4-Chlorotoluene',
       '4-Isopropyltoluene', 'Benzene', 'Bromobenzene',
       'Bromochloromethane', 'Bromomethane', 'Carbon tetrachloride',
       'Chlorobenzene', 'Chloroethane', 'Chloromethane', 'Dibromomethane',
       'Dichlorodifluoromethane', 'Ethyl benzene', 'Hexachlorobutadiene',
       'Isopropylbenzene', 'Methyl tert-butyl ether (MTBE)',
       'Methylene chloride', 'Naphthalene', 'Styrene',
       'Tetrachloroethene', 'Toluene', 'Trichloroethene',
       'Trichlorofluoromethane', 'Vinyl chloride',
       'cis-1,2-Dichloroethene', 'cis-1,3-Dichloropropene',
       'm + p Xylene', 'n-Butylbenzene', 'n-Propylbenzene', 'o-Xylene',
       'sec-Butylbenzene', 'tert-Butylbenzene',
       'trans-1,2-Dichloroethene', 'trans-1,3-Dichloropropene',
       'Total ortho-Phosphate', 'Escherichia coli', '2,4,5-T',
       '2,4,5-TP (Silvex)', '2,4-D', '2,4-DB', '3-Hydroxycarbofuran',
       'Alachlor', 'Aldicarb', 'Aldicarb sulfone', 'Aldicarb sulfoxide',
       'Aldrin', 'Atrazine', 'Azinphos methyl (Guthion)', 'BHC-alpha',
       'BHC-beta', 'BHC-delta', 'BHC-gamma (Lindane)', 'Benfluralin',
       'Bromacil', 'Captan', 'Carbaryl', 'Carbofuran',
       'Carbophenothion (Trithion)', 'Chlordane', 'Chlorothalonil',
       'Chlorpropham', 'Chlorpyrifos', 'Cyanazine', 'Dacthal (DCPA)',
       'Demeton (Demeton O + Demeton S)', 'Diazinon', 'Dicamba',
       'Dichloran', 'Dichlorprop', 'Dicofol', 'Dieldrin', 'Dimethoate',
       'Dinoseb (DNPB)', 'Dissolved Chromium, hexavalent (Cr6+)',
       'Disulfoton', 'Diuron', 'Endosulfan sulfate', 'Endosulfan-I',
       'Endosulfan-II', 'Endrin', 'Endrin aldehyde', 'Ethion',
       'Glyphosate', 'Heptachlor', 'Heptachlor epoxide', 'MCPA', 'MCPP',
       'Malathion', 'Methidathion', 'Methomyl', 'Methoxychlor',
       'Metolachlor', 'Mevinphos', 'Naled', 'Napropamide', 'Norflurazon',
       'Oxamyl', 'Oxyfluorfen', 'PCB-1016', 'PCB-1221', 'PCB-1232',
       'PCB-1242', 'PCB-1248', 'PCB-1254', 'PCB-1260', 'Parathion, Ethyl',
       'Parathion, Methyl', 'Pendimethalin',
       'Pentachloronitrobenzene (PCNB)', 'Pentachlorophenol (PCP)',
       'Phorate', 'Phosalone', 'Phosmet', 'Picloram', 'Profenofos',
       'Prometryn', 'Propetamphos', 'Simazine', 'Thiobencarb',
       'Toxaphene', 'Triclopyr', 'Trifluralin', "p,p'-DDD", "p,p'-DDE",
       "p,p'-DDT", 's,s,s-Tributyl Phosphorotrithioate (DEF)',
       'Ethylene Dibromide', 'm-Xylene', 'p-Xylene',
       'Aminomethylphosphonic Acid (AMPA)', 'Formetanate hydrochloride',
       'Methiocarb', 'Asbestos, Chrysotile',
       'Chlorinated Hydrocarbons (General)', 'DDD (all isomers)',
       'DDT (all isomers)', 'Atrazine-Simazine Mix', 'BHC',
       'Dissolved Bismuth', 'Dissolved Cobalt', 'Dissolved Gallium',
       'Dissolved Germanium', 'Dissolved Vanadium', 'Dissolved Titanium',
       'DDE (all isomers)', 'Dissolved Acid Hydrolyzable Phosphorus',
       'Phenols', 'Phenol', 'Bromochloroacetic Acid (BCAA)',
       'Dibromoacetic Acid (DBAA)', 'Dichloroacetic Acid (DCAA)',
       'Monobromoacetic Acid (MBAA)', 'Monochloroacetic Acid (MCAA)',
       'Trichloroacetic Acid (TCAA)',
       'Organic Phosphorus Pesticides (OPP)', 'Phenoxy Growth Regulators',
       'Chlorophyll a', 'Pheophytin a', '4-Bromofluorobenzene',
       '1,1,2-Trichlorotrifluoroethane', 'Chloropicrin', 'Chorpropham',
       'Ethylbenzene', 'Tetrachloroethylene', 'Tetrachlorofluoromethane',
       'Total Xylene, (total)', 'Total Phenols',
       '(Aminomethyl)phosphonic acid', '1-Naphthol', 'Acephate',
       'Dichloroprop', 'Propargite',
       '2,3,7,8-Tetrachlorodibenzo-p-dioxin', 'Acifluorfen', 'Bentazon',
       'Benzo(a)pyrene', 'Bis(2-ethylhexyl) adipate',
       'Bromochloroacetonitrile', 'Butachlor', 'Dalapon',
       'Dibromoacetonitrile', 'Dichloroacetonitrile', 'Diquat',
       'Dissolved Thallium', 'Endothal', 'Ethylenethiourea',
       'Hexachlorobenzene', 'Hexachlorocyclopentadiene', 'Metribuzin',
       'Molinate', "PCB's", 'Propachlor', 'Total Asbestos, Chrysotile',
       'Total Cyanide', 'Trichloroacetonitrile',
       'bis(2-Ethylhexyl) phthalate', '3,5-Dichlorobenzoic Acid',
       '4-Nitrophenol', 'Bolstar', 'Coumaphos', 'Demeton-O', 'Demeton-S',
       'Dichlorvos', 'Ethoprop', 'Fensulfothion', 'Fenthion', 'Merphos',
       'Propoxur', 'Ronnel', 'Tetrachlorvinphos', 'Thionazine (Zinophos)',
       'Tokuthion', 'Total Parathion, ethyl & methyl', 'Trichloronate',
       'Esfenvalerate', 'Permethrin', "o,p'-DDE", 'Chloropropham',
       'Dioxathion', 'Total Thallium', 'Propanil', 'Methamidophos',
       'Propham', 'Dicrotophos', 'Dissolved Lithium',
       'Purgeable Halocarbons', '2,3-Dibromopropionic acid',
       'Ash Free Dry Mass', 'Soil Solids', 'Volatile Solids',
       'Settleable Solids', 'Dissolved Bicarbonate (HCO3-)',
       'Dissolved Carbonate (CO3--)', 'Dissolved Hydroxide (OH-)',
       'Dissolved Strontium', 'Dissolved Organic Nitrogen',
       'Total Calcium', 'Total Magnesium', 'Filtered Water Turbidity',
       'Chemical Oxygen Demand (COD)', 'Total Oil and Grease', 'Cyanide',
       'Dissolved Tin', 'Total Boron', 'Total Cobalt', 'Total Molybdenum',
       'Total Potassium', 'Total Sodium', 'Total Tin', 'Total Vanadium',
       '6-Day Biochemical Oxygen Demand',
       'Fibers > 10   ?m Asbestos, Chrysotile',
       '7-Day Biochemical Oxygen Demand', 'Tannin and Lignin',
       'Dissolved Total Kjeldahl Nitrogen', 'Biochemical Oxygen Demand',
       'Carbonaceous Biochemical Oxygen Demand', 'Perthane',
       'Endosulfan (mixed isomers)', 'Telodrin',
       'Inositol 1,4,5-Trisphosphate', 'Total Silica (SiO2)',
       '4-Day Biochemical Oxygen Demand', 'Total Bismuth',
       'Total Gallium', 'Total Germanium', 'Total Titanium',
       'Total Sulfides', 'Tetrachlorophenols', 'Bicarbonate (HCO3-)',
       'Metalaxyl', '2-Chloroallyl diethyldithiocarbamate (CDEC)',
       'Phorate Sulfone', "o,p'-DDD", "o,p'-DDT",
       'TEPP (Tetraethyl Pyrophosphate)', "4,4'-Dibromoctafluorobiphenyl",
       'Diesel Range Organics (C-10-C-28)', 'Gasoline (C4-C12)',
       'Tetradifon (Tedion)', 'Captafol', 'Cryptosporidium',
       'Giardia lamblia', 'Clostridium perfringens', 'Fecal Coliform',
       'Total Coliform', 'Thiodicarb',
       'Suspended + Volatile Suspended Solids', 'Sulfallate',
       '2,3,6-Trichlorobenzoic Acid', 'Acenaphthene', 'Acenaphthylene',
       'Anthracene', 'Benz(a)anthracene', 'Benzo(b)fluoranthene',
       'Benzo(ghi)perylene', 'Benzo(k)fluoranthene', 'Chrysene',
       'Dibenz(a,h)anthracene', 'Fluoranthene', 'Fluorene',
       'Indeno(1,2,3-cd)pyrene', 'Phenanthrene', 'Pyrene',
       'Xylene, (total)', 'Allethrin', 'Bifenthrin', 'Cyfluthrin',
       'Cypermethrin', 'Deltamethrin/Tralomethrin', 'Fenvalerate',
       'Prallethrin', 'Sumithrin', 'Tefluthrin', 'l-Cyhalothrin',
       '100-Day Biochemical Oxygen Demand', 'Bromide',
       'Total Total Kjeldahl Nitrogen', 'Dissolved Methylmercury',
       'Total Methylmercury',
       'Haloacetic Acid Formation Potential (HAAFP)',
       'Trihalomethane Formation Potential (THMFP)', 'Pronamide',
       'Dichloropropane - dichloropropene (D-D Mixture)', 'Dichlone',
       'Butyl benzyl phthalate', 'Di-n-butyl phthalate',
       'Di-n-octyl phthalate', 'Diethyl phthalate', 'Dimethyl phthalate'],
      dtype=object)

In [295]:
water_q_param = [
    'Oil and Grease',
    'Total Suspended Solids',
    'Total Ammonia',
    'Total Phosphorus',
    'Chlorophyll a',
    'Chemical Oxygen Demand (COD)',
    'Fecal Coliform'
]

In [296]:
df = df[df['parameter'].isin(water_q_param)]

In [297]:
df['parameter'].unique()

array(['Total Ammonia', 'Oil and Grease', 'Total Phosphorus',
       'Total Suspended Solids', 'Chlorophyll a',
       'Chemical Oxygen Demand (COD)', 'Fecal Coliform'], dtype=object)

In [298]:
df.head()

,station_type,latitude,longitude,county_name,parameter,result,units
11514,Surface Water,37.7833,-121.5908,Alameda,Total Ammonia,.01,mg/L as N
11523,Surface Water,37.7833,-121.5908,Alameda,Total Ammonia,.05,mg/L as N
11533,Surface Water,37.7833,-121.5908,Alameda,Total Ammonia,< R.L.,mg/L as N
11546,Surface Water,37.7833,-121.5908,Alameda,Oil and Grease,< R.L.,mg/L
11547,Surface Water,37.7833,-121.5908,Alameda,Total Ammonia,.22,mg/L as N

In [299]:
alamda = df[(df['parameter']=='Oil and Grease')]
alamda['result'].unique()

array(['< R.L.', '1', '7', '2', '4', '5', '12', '10', '6', '3', '43', '9',
       '30', '8', '17', '21', '41', '20', '98', '16', '74', '36', '32',
       '24', '33', '26', '61', '63', '35', '13', '126', '66', '15', '11',
       '27', '48', '72', '18', '14', '28', '22', '82', '34', '411', '78',
       '81', '58', '138', '44', '40', '57', '92', '65', '147', '53',
       '174', '46', '80', '178', '45', '51', '110', '136', '88', '52',
       '108', '180', '31', '64', '160', '70', '310', '199', '130', '77',
       '222', '365', '89', '182', '69', '103', '105', '99', '106', '75',
       '131', '240', '100', '173', '90', '260', '140', '210', '19', '59',
       '300', '165', '56', '79', '220', '120', '55', '37', '50'],
      dtype=object)

In [300]:
df = df[(df['result'] != '< R.L.')]
df = df[(df['result']!= '< MDL, MDL = 0.041')]
df = df[(df['result']!= '< MDL, MDL = 2.5')]
df = df[(df['result']!= '< MDL, MDL = 3.3')]
df = df[(df['result']!= '<R.L.')]

In [301]:
alamda = df[(df['result']=='< MDL, MDL = 0.041')]
alamda['result'].unique()
print (df['result'].unique().tolist())

['.01', '.05', '.22', '1', '.12', '.122', '65.3', '72.3', '.047', '.06', '2', '.02', '4', '.03', '3', '.08', '36.4', '.04', '25', '5', '.062', '16.1', '18.8', '3.2', '9', '.043', '5.3', '14', '3.3', '.045', '7', '.029', '.021', '22', '.034', '.07', '10', '.039', '.064', '.09', '.27', '.019', '.13', '.012', '.036', '.053', '.025', '.11', '.1', '.42', '.16', '.24', '.41', '.34', '.15', '.26', '.36', '.3', '.57', '.32', '.53', '.56', '.52', '.39', '.49', '.43', '.29', '1.53', '.35', '1.01', '.21', '.59', '.95', '.68', '1.5', '1.57', '.25', '1.47', '.78', '1.21', '5.22', '.46', '.62', '2.1', '.31', '.33', '.72', '1.27', '.19', '1.37', '.18', '.17', '.14', '8', '.2', '12', '3.34', '16', '.323', '57', '2.07', '.327', '.28', '67', '.139', '6.5', '15', '30', '6', '.89', '.114', '3.85', '.173', '.095', '12.4', '24', '22.4', '29', '.218', '3.88', '.072', '28', '.133', '33', '97.01', '.187', '18.9', '11', '26', '3.24', '.186', '.066', '10.1', '.069', '3.6', '32', '1.69', '.112', '17', '.363', '4.96', '15.9', '1.39', '.103', '18', '.085', '.69', '13', '.076', '3.4', '36', '.088', '10.6', '.078', '.111', '11.6', '4.4', '2.68', '.091', '.61', '.108', '.99', '.124', '27', '7.9', '44', '38', '40', '.106', '1.33', '.147', '2.53', '.092', '2.78', '2.84', '.096', '.101', '1.79', '19', '.107', '9.2', '2.64', '.163', '1.68', '12.39', '5.75', '.117', '10.9', '13.6', '.151', '2.18', '6.4', '64.4', '.299', '37', '.093', '12.02', '.129', '.235', '10.8', '12.6', '.152', '35', '1.92', '.158', '.094', '4.7', '.086', '3.83', '.083', '.082', '2.8', '1.71', '3.8', '.105', '2.6', '.83', '.099', '113', '.84', '11.5', '.061', '4.3', '4.1', '.96', '.067', '.5', '8.87', '.056', '45', '2.5', '4.8', '5.4', '7.6', '1.06', '29.1', '.055', '23', '8.11', '2.87', '1.59', '5.64', '2.27', '3.25', '1.56', '2.25', '3.17', '.6', '1.96', '3.29', '3.02', '4.09', '10.16', '5.46', '4.81', '4.05', '3.16', '.91', '1.1', '2.21', '3.48', '1.35', '2.61', '1.61', '3.84', '6.31', '7.83', '6.51', '9.23', '9.87', '7.16', '8.97', '19.2', '8.21', '3.75', '2.41', '3.54', '2.74', '1.98', '1.26', '1.87', '1.97', '2.85', '58', '59', '41.1', '.164', '24.4', '8.8', '.155', '.161', '.109', '.23', '63', '.104', '17.5', '.138', '20.2', '20', '.079', '.071', '.098', '2.9', '21', '5.8', '.084', '46', '18.4', '53', '14.5', '28.4', '6.6', '6.7', '31', '15.5', '.205', '.185', '23.3', '34', '.123', '.126', '.298', '11.4', '8.6', '3.1', '.065', '13.2', '4.9', '.121', '7.7', '.063', '.041', '3.7', '42', '.057', '.089', '6.2', '.73', '.67', '.206', '.311', '.321', '.445', '.195', '.87', '.031', '.498', '.54', '.199', '.054', '.316', '.027', '.046', '.059', '.058', '.035', '87', '154', '210', '50', '240', '.024', '135', '39', '199', '5.1', '95', '.016', '.023', '318', '3.5', '14.6', '7.3', '.014', '8.2', '31.7', '.013', '12.2', '122', '88', '91', '145', '.94', '1.8', '4.6', '.156', '28.1', '124', '52', '654', '.052', '103', '64', '933', '947', '49', '.011', '.022', '69', '60', '.45', '378', '732', '745', '753', '171', '51', '48', '77', '47', '144', '392', '394', '70', '78', '580', '.51', '61', '148', '55', '80', '.4', '43', '41', '85', '512', '300', '360', '350', '270', '244', '430', '365', '414', '408', '382', '354', '352', '198', '74', '54', '683', '230', '443', '525', '274', '203', '119', '65', '99', '111', '147', '93', '62', '75', '76', '56', '263', '.37', '207', '214', '.018', '6.1', '.017', '.015', '2.7', '6.3', '7.8', '9.5', '4.2', '6.9', '8.4', '.563', '7.1', '3.9', '5.7', '6.8', '.026', '15.1', '.033', '.028', '29.2', '8.1', '102', '18.6', '9.8', '38.8', '13.4', '10.2', '8.3', '4.5', '5.9', '.087', '1.3', '.38', '1.6', '.65', '.88', '.048', '.077', '.097', '.75', '.44', '172', '303', '.47', '72', '.58', '.8', '235', '5.2', '137', '100', '7.2', '66', '204', '312', '1.2', '926', '96', '16.2', '173', '15.2', '18.2', '97', '324', '232', '233', '139', '90', '68', '358', '92', '502', '216', '94', '150', '151', '.48', '.7', '376', '118', '134', '266', '272', '246', '1.4', '10.61', '23.5', '6.41', '59.3', '.984', '293.3', '5.39', '.202', '4.02', '38.1', '32.1', '.276', '3.74', '.146', '8.17', '.181', '56.4', '2.03', '.145', '2.79', '.209', '51.5', '3.49', '.118', '7.05', '27.5', '16.02', '.184', '32.2', '58.9', '.125', '26.9', '.183', '33.1', '364', '368', '.113', '.075', '.049', '.074', '.032', '1.25', '10.4', '5.6', '3.86', '1.22', '.85', '1.9', '1.95', '1.45', '.252', '.253', '37.1', '1.84', '1.23', '3.51', '.81', '1.14', '2.24', '6.16', '44.3', '.74', '1.13', '3.63', '20.8', '11.2', '.9', '3.89', '1.05', '2.92', '.76', '2.97', '2.77', '2.44', '4.97', '15.8', '9.19', '6.46', '8.48', '8.9', '3.04', '28.5', '23.6', '24.2', '2.54', '9.7', '6.28', '8.7', '3.08', '1.34', '7.15', '1.99', '1.36', '2.38', '1.64', '1.65', '1.51', '16.7', '1.18', '.82', '.66', '.71', '1.08', '1.11', '2.23', '1.46', '1.24', '6.33', '33.6', '1.16', '1.15', '3.23', '1.09', '11.1', '1.42', '1.85', '2.28', '.97', '5.01', '4.77', '16.6', '2.56', '7.02', '5.36', '3.27', '7.53', '9.1', '2.66', '1.73', '1.32', '2.55', '7.21', '3.43', '1.54', '8.53', '1.52', '2.39', '.98', '1.03', '1.38', '.068', '3.09', '4.47', '.119', '.64', '3.59', '10.7', '5.25', '4.45', '5.68', '2.65', '.102', '12.1', '2.75', '.416', '1.93', '.116', '3.81', '14.8', '12.52', '.134', '9.4', '7.19', '.137', '27.2', '29.4', '6.36', '.127', '13.7', '5.74', '3.77', '13.8', '7.63', '1.49', '4.33', '1.88', '1.83', '1.12', '14.9', '8.5', '2.3', '1.78', '2.52', '1.02', '1.43', '.93', '80.5', '1.91', '1.19', '2.16', '.79', '.92', '1.29', '15.7', '1.94', '1.58', '1.48', '2.32', '1.74', '1.44', '4.06', '1.75', '2.47', '3.38', '2.34', '2.37', '3.32', '1.76', '2.05', '8.86', '2.04', '2.42', '6.19', '7.69', '20.4', '25.61', '3.47', '4.69', '2.49', '32.47', '3.65', '1.89', '18.14', '21.9', '2.09', '3.87', '1.67', '4.37', '2.31', '17.3', '14.4', '14.7', '3.35', '3.69', '3.15', '2.48', '3.28', '4.16', '5.33', '2.86', '10.89', '6.64', '4.55', '4.03', '4.14', '3.71', '8.65', '5.77', '3.56', '1.17', '3.78', '6.84', '11.3', '4.24', '5.41', '4.25', '3.73', '4.34', '3.05', '5.98', '2.17', '2.08', '2.2', '9.9', '7.48', '3.19', '4.57', '2.46', '2.96', '5.16', '1.77', '17.9', '1.81', '1.82', '12.8', '1.63', '21.8', '4.36', '20.7', '.77', '1.66', '3.01', '.86', '42.5', '1.28', '.142', '2.15', '2.89', '.038', '42.6', '3.07', '2.83', '2.02', '6.24', '3.22', '5.32', '7.89', '3.39', '5.29', '10.81', '4.15', '4.18', '15.76', '4.26', '5.23', '2.81', '6.35', '2.13', '2.72', '22.43', '2.33', '2.06', '91.1', '.132', '3.21', '2.22', '4.62', '6.09', '3.79', '1.04', '5.94', '1.31', '23.55', '11.79', '4.95', '1.62', '2.63', '2.95', '3.06', '6.97', '19.06', '4.32', '54.68', '2.12', '3.57', '2.26', '22.62', '3.66', '2.29', '2.11', '4.08', '1.07', '1.41', '1.55', '6.82', '28.6', '3.33', '.051', '40.37', '3.31', '41.95', '7.58', '24.79', '1.7', '2.14', '4.84', '4.17', '5.18', '14.55', '3.03', '6.75', '2.36', '19.5', '2.71', '6.43', '1.72', '6.23', '12.13', '4.86', '5.07', '5.45', '28.3', '3.93', '2.98', '2.35', '12.74', '13.3', '2.51', '28.36', '83.34', '2.88', '5.5', '7.4', '18.08', '2.45', '3.92', '10.22', '4.92', '6.38', '11.9', '3.62', '9.72', '5.19', '74.23', '4.21', '229', '9.71', '.342', '73.9', '9.6', '17.1', '9.3', '22.9', '23.7', '73', '180', '2.19', '5.13', '4.23', '.159', '.148', '12500', '156', '158', '1107', '222', '169', '132', '8430', '.115', '.274', '.037', '196', '340', '311', '187', '193', '451', '453', '83', '296', '84', '215', '114', '116', '123', '236', '2.4', '71', '130', '98', '760', '9.93', '5.66', '13.5', '.63', '162', '5.82', '317', '2.69', '339', '202', '466', '257', '197', '237', '238', '314', '109', '108', '271', '185', '407', '346', '152', '327', '191', '7.14', '125.51', '64.3', '52.9', '66.1', '83.2', '68.3', '63.3', '82.8', '62.6', '48.2', '60.5', '104', '49.5', '45.2', '33.9', '.55', '45.8', '90.8', '61.5', '107', '106', '50.8', '540', '4.46', '3.37', '93.6', '24.7', '73.1', '57.9', '62.2', '34.8', '30.7', '47.2', '39.6', '51.9', '40.2', '41.2', '59.1', '34.1', '28.9', '39.1', '39.8', '26.4', '12.7', '29.9', '48.6', '33.7', '12.98', '6.02', '27.3', '27.6', '351', '51.2', '53.6', '30.9', '31.3', '189', '208', '42.4', '44.4', '23.1', '23.8', '7.5', '27.9', '583', '22.2', '14.1', '.044', '15.6', '179', '22.8', '43.9', '.165', '17.2', '.913', '40.4', '24.6', '12.3', '21.5', '121', '19.8', '21.7', '51.6', '105', '112', '82', '.348', '.307', '.666', '11.7', '.222', '97.1', '24.8', '33.8', '29.3', '.144', '.149', '.128', '.172', '.136', '.175', '.143', '.968', '.496', '.358', '.192', '.379', '.336', '.338', '.495', '7.77', '.131', '520', '746', '1525', '241', '289', '484', '4.04', '2.94', '140', '136', '117', '194', '221', '149', '330', '133', '3.42', '469', '170', '164', '115', '2.99', '178', '146', '110', '218', '4.43', '125', '168', '126', '120', '201', '4.12', '143', '707', '4.19', '692', '127', '181', '138', '142', '153', '370', '89', '436', '141', '333', '21.06', '81', '212', '101', '871', '496', '38.7', '652', '98.7', '990', '131', '129', '15.3', '242', '661', '810', '111.6', '690', '90.7', '343', '67.1', '490', '102.1', '474', '980', '167', '788', '21.3', '316', '52.1', '551', '743', '175', '86', '177', '322', '79', '4.35', '6.76', '128', '2.57', '5.28', '292', '157', '695', '262', '532', '165', '256', '213', '359', '225', '161', '85.4', '56.2', '5.24', '55.4', '411', '182', '58.3', '259', '43.5', '87.9', '70.2', '36.5', '9.32', '35.8', '74.9', '23.33', '186', '3.11', '52.5', '174', '155', '57.5', '58.8', '75.7', '67.4', '34.5', '14.2', '48.3', '42.1', '36.1', '38.5', '6.21', '40.7', '92.6', '190', '75.1', '95.8', '54.1', '388', '946', '62.7', '280', '84.2', '41.8', '35.7', '6.81', '19.6', '24.3', '163', '60.4', '159', '40.9', '49.3', '99.2', '35.6', '32.6', '160', '310', '260', '220', '6.61', '7.84', '5.67', '16.3', '209', '16.15', '5.12', '30.6', '6.06', '6.29', '6.52', '79.5', '6.37', '37.9', '29.7', '6.99', '7.61', '34.2', '5.51', '176', '33.2', '28.7', '47.9', '38.4', '21.2', '39.7', '568', '977', '184', '530', '72.1', '440', '6.01', '610', '254', '457', '38.6', '452', '550', '77.5', '735', '1470', '491', '389', '590', '395', '428', '434', '651', '36.9', '621', '47.3', '478', '470', '587', '799', '533', '460', '166', '518', '2.73', '504', '420', '528', '372', '195', '435', '1200', '390', '20.9', '413', '450', '449', '554', '613', '495', '465', '250', '537', '44.9', '319', '321', '89.4', '285', '61.4', '659', '67.8', '50.6', '206', '67.5', '856', '523', '1820', '630', '582', '87.6', '224', '374', '563', '264', '5.55', '391', '267', '18.33', '10.69', '27.7', '9.16', '10.01', '18.01', '10.87', '4.66', '6.68', '6.13', '16.31', '22.91', '13.74', '14.91', '16.38', '14.82', '13.59', '1.86', '8.08', '16.69', '8.62', '8.23', '18.25', '12.85', '5.35', '4.61', '7.76', '406', '399', '400', '366', '412', '524', '446', '795', '34.6', '7.86', '49.2', '445', '59.6', '24.1', '3.58', '25.2', '12.42', '17.89', '16.93', '31.6', '13.98', '13.67', '23.72', '13.51', '3.36', '27.4', '19.03', '11.8', '13.9', '15.37', '23.4', '14.37', '13.43', '437', '8.93', '11.03', '11.26', '10.09', '9.43', '10.56', '39.2', '4.58', '13.66', '11.25', '17.86', '5.05', '3.68', '9.27', '20.58', '15.07', '10.79', '640', '10.72', '17.4', '573', '3.96', '10.51', '10.64', '67.6', '5.44', '25.7', '8.39', '20.6', '20.1', '4.59', '39.5', '17.48', '24.07', '21.74', '8.31', '11.65', '7.45', '10.48', '12.58', '86.5', '67.7', '85.3', '205', '623', '60.3', '31.9', '284', '1400', '3200', '60.2', '12.5', '44.6', '13.42', '4.27', '18.63', '5.15', '4.82', '2.76', '22.6', '12.9', '22.7', '243', '305', '219', '188', '328', '65.8', '336', '5.54', '442', '.193', '.272', '.207', '18.5', '.273', '.216', '.246', '.162', '.153', '.178', '.244', '.154', '.243', '21.1', '22.1', '.217', '.081', '.782', '21.6', '.157', '34.7', '23.2', '2.43', '.315', '20.3', '.166', '9.01', '6.25', '4.64', '4.53', '7.07', '16.44', '11.43', '.135', '5.47', '5.57', '2.01', '7.78', '3.95', '5.14', '50.5', '.201', '.237', '527', '531', '13.1', '448', '357', '66.7', '.331', '.334', '33.3', '78.9', '5.56', '98.5', '59.8', '4.38', '20.26', '57.2', '8.76', '7.35', '3.98', '3.26', '.197', '.567', '.073', '.607', '.042', '.349', '54.4', '.191', '107.6', '108.6', '2.59', '3.52', '5.86', '4.07', '4.89', '18.7', '5.62', '3.12', '3.46', '2.93', '3.91', '5.21', '3.18', '29.8', '.319', '2.62', '.356', '7.22', '4.79', '32.9', '.775', '8.68', '3.13', '.655', '32.3', '.419', '.407', '7.06', '11.37', '6.27', '5.84', '906', '1120', '258', '18.3', '16.4', '17.7', '16.8', '2.67', '81.4', '12.36', '33.43', '40.69', '7.33', '16.59', '8.66', '8.49', '4.85', '5.76', '5.87', '12.43', '4.29', '10.3', '.189', '4.13', '37.5', '5.59', '4.56', '5.02', '5.34', '5.37', '4.22', '7.62', '3.82', '3.53', '4.49', '3.44', '275', '19.4', '.463', '81.5', '.291', '.174', '88.2', '.176', '19.1', '26.7', '39.3', '.286', '32.7', '63.4', '27.8', '.282', '.248', '120.9', '.254', '98.2', '.516', '8.04', '7.52', '6.08', '26.05', '19.3', '25.9', '10.42', '25.3', '16.53', '18.1', '15.97', '29.5', '16.9', '23.9', '19.04', '18.91', '22.5', '15.68', '18.49', '18.21', '7.68', '9.77', '41.5', '35.3', '35.2', '43.4', '38.3', '230000', '80000', '1300', '30000', '170000', '17000', '410', '300000', '5000', '192', '50000', '8000', '700000', '130000', '8.07', '7.94', '.685', '4.54', '.249', '14.39', '55.2', '92.9', '15.81', '46.4', '4.73', '4.39', '7.49', '12.07', '7.36', '41.44', '52.4', '9.92', '6.72', '8.06', '8.38', '10.15', '2.91', '4.91', '5.11', '3.76', '7.42', '11.75', '5.27', '6.39', '96.6', '8.12', '7.26', '4.83', '4.41', '13.46', '5.96', '26.8', '10.68', '9.29', '6.03', '8.51', '6.94', '6.14', '34.3', '6.73', '5.93', '30.2', '5.89', '6.62', '6.45', '4.52', '4.93', '6.48', '8.81', '9.08', '28.84', '14.85', '5.42', '40.65', '6.17', '24.56', '74.55', '4.51', '5.03', '8.54', '17.8', '8.95', '5.48', '13.88', '3.14', '35.9', '62.8', '7.37', '13.14', '8.67', '25.5', '10.53', '30.12', '4.01', '52.12', '6.57', '9.13', '8.92', '29.85', '16.55', '5.09', '17.09', '10.57', '16.5', '96.1', '56.1', '4.76', '5.78', '4.63', '5.08', '22.32', '37.8', '20.5', '5.31', '8.29', '3.72', '8.33', '9.02', '7.17', '21.98', '7.43', '30.72', '51.3', '23.26', '14.42', '4.44', '9.24', '14.86', '11.32', '6.42', '9.18', '5.61', '3.67', '9.22', '6.88', '8.28', '8.44', '14.15', '9.51', '4.68', '6.44', '7.44', '6.66', '39.47', '54.11', '8.02', '15.71', '15.82', '7.98', '.748', '.236', '.306', '.459', '9.84', '.245', '.247', '.194', '10.47', '31.5', '8.75', '39.52', '46.35', '19.7', '46.52', '9.67', '35.31', '74.3', '5.26', '9.68', '13.13', '5.38', '17.6', '8.73', '90.78', '8.22', '96.69', '5.53', '17.41', '.433', '13.56', '5.43', '6.18', '4.99', '18.69', '11.96', '11.76', '6.85', '26.56', '28.94', '14.26', '10.5', '53.4', '19.43', '73.63', '3.64', '81.81', '5.95', '26.03', '13.24', '16.25', '19.86', '40.6', '36.45', '6.98', '94.42', '45.3', '74.79', '106.59', '60.66', '79.84', '90.89', '54.04', '31.12', '74.05', '15.93', '9.59', '27.1', '9.44', '4.88', '.188', '7.92', '13.45', '30.38', '.219', '8.15', '17.05', '12.23', '8.63', '13.99', '6.54', '.308', '.211', '15.42', '3.94', '15.38', '30.22', '8.01', '61.1', '12.71', '5.65', '50.41', '33.64', '22.96', '15.4', '19.14', '18.26', '15.15', '31.61', '40.27', '14.74', '76.16', '84.59', '10.04', '80.31', '79.7', '13.77', '25.6', '43.04', '23.28', '3.55', '103.81', '91.42', '20.14', '5.06', '24.67', '53.5', '130.4', '22.75', '18.05', '5.99', '75.19', '47.4', '32.57', '63.87', '4.11', '21.89', '14.31', '183.7', '57.6', '94.52', '16.98', '8.35', '17.52', '45.9', '59.5', '152.19', '38.13', '8.41', '142.98', '72.8', '6.95', '210.4', '67.3', '7.97', '88.64', '42.9', '129.59', '13.29', '31.8', '52.55', '83.8', '103.6', '17.11', '24.03', '20.62', '56.6', '85.06', '19.33', '20.21', '8.14', '25.4', '25.63', '68.7', '102.2', '17.84', '65.7', '35.1', '28.8', '62.01', '52.8', '14.52', '11.85', '44.1', '16.23', '10.36', '64.22', '30.33', '32.5', '7.87', '45.82', '35.5', '66.8', '176.22', '14.04', '41.04', '70.5', '15.11', '14.79', '34.79', '32.89', '90.6', '34.4', '8.36', '9.61', '11.11', '26.2', '18.37', '11.53', '7.32', '31.51', '30.61', '9.12', '5.88', '27.76', '28.09', '15.59', '8.79', '7.65', '26.24', '23.39', '27.77', '63.8', '73.8', '56.3', '7.96', '19.9', '30.65', '14.3', '30.4', '51.7', '32.04', '148.78', '36.2', '64.5', '73.2', '12.14', '51.8', '76.7', '95.4', '99.1', '56.8', '48.7', '87.8', '208.26', '29.6', '34.39', '21.79', '50.3', '9.35', '9.97', '86.1', '19.76', '6.78', '11.08', '43.52', '12.99', '43.6', '24.5', '7.73', '40.3', '5.71', '7.72', '25.85', '43.36', '9.88', '186.37', '3.41', '95.3', '9.83', '28.41', '6.65', '15.27', '27.01', '12.28', '9.85', '22.08', '16.62', '63.01', '17.08', '45.07', '37.17', '97.4', '22.83', '49.85', '64.1', '56.18', '28.29', '50.84', '21.4', '6.53', '75.6', '4.42', '8.88', '18.99', '46.78', '4.78', '20.83', '36.21', '31.4', '95.14', '87.58', '78.39', '106.37', '89.39', '16.77', '89.1', '145.78', '140.44', '238.7', '72.2', '31.69', '110.54', '12.51', '57.1', '63.6', '57.46', '152.09', '36.3', '92.1', '56.29', '189.57', '34.71', '10.29', '21.27', '79.1', '268', '78.2', '13.39', '69.9', '53.61', '85.44', '105.2', '54.6', '239', '11.89', '325', '223', '65.5', '78.5', '76.9', '77.6', '51.78', '184.07', '61.73', '30.87', '37.6', '73.95', '90.25', '86.72', '101.46', '59.2', '30.1', '87.2', '16.66', '44.7', '60.45', '64.88', '37.7', '66.85', '36.53', '14.92', '79.8', '17.07', '48.9', '83.3', '30.95', '8.19', '76.1', '58.74', '41.3', '26.17', '63.2', '38.29', '51.68', '28.11', '109.2', '44.22', '9.79', '5.85', '39.4', '35.67', '22.53', '7.31', '6.67', '3.97', '17.19', '31.19', '7.28', '8.57', '9.56', '70.8', '33.4', '37.3', '57.3', '55.82', '22.3', '4.71', '1710', '4.31', '4.72', '13.11', '31.35', '30.83', '55.04', '64.93', '48.59', '40.8', '90.67', '13.03', '66.2', '63.1', '95.91', '101.57', '65.1', '58.6', '9.03', '91.6', '29.37', '90.14', '69.2', '26.06', '43.57', '30.54', '41.6', '73.48', '82.98', '44.43', '126.02', '187.43', '86.2', '49.56', '193.37', '78.8', '49.1', '32.15', '269', '55.3', '88.1', '20.43', '70.3', '92.38', '48.5', '66.5', '83.56', '30.01', '41.4', '236.73', '16.87', '97.2', '41.9', '36.7', '84.6', '27.87', '90.4', '20.08', '24.9', '217', '28.52', '19.01', '37.49', '36.95', '47.6', '38.2', '25.42', '41.62', '7.27', '24.14', '17.62', '25.1', '11.21', '46.6', '34.19', '51.13', '70.49', '26.81', '17.98', '13.97', '2.58', '26.3', '7.88', '27.02', '14.47', '16.29', '29.16', '12.82', '21.47', '7.75', '7.74', '5.83', '5.92', '75.2', '288', '52.6', '13.28', '32.62', '20.91', '66.64', '6.15', '35.46', '9.98', '173.74', '10.03', '17.51', '18.35', '10.05', '38.72', '21.26', '45.4', '11.64', '91.66', '5.79', '50.13', '41.87', '7.64', '39.63', '5.91', '4.74', '5.72', '8.26', '24.46', '6.56', '55.11', '6.87', '50.1', '71.77', '9.52', '46.3', '39.73', '3.61', '59.81', '52.97', '57.89', '62.5', '72.4', '10.38', '98.26', '66.6', '26.1', '7.47', '148.86', '11.07', '6.34', '68.83', '14.28', '63.9', '69.7', '46.1', '53.83', '19.12', '18.48', '32.8', '55.8', '46.7', '41.01', '86.24', '62.4', '87.21', '40.5', '13.78', '19.22', '61.94', '11.39', '10.25', '7.85', '54.37', '25.96', '15.87', '7.95', '24.16', '8.84', '9.41', '15.49', '7.91', '27.34', '7.04', '8.13', '8.89', '19.97', '46.46', '73.37', '46.56', '14.63', '101.89', '8.52', '77.4', '30.97', '7.56', '88.5', '25.74', '56.82', '62.48', '56.5', '48.1', '124.96', '80.1', '191.71', '9.75', '31.72', '14.56', '49.4', '61.9', '84.7', '33.5', '43.25', '18.58', '59.9', '45.1', '47.72', '68.6', '11.35', '12.18', '20.93', '20.61', '16.91', '21.15', '17.27', '8.25', '7.51', '9.04', '29.26', '13.08', '7.93', '8.69', '17.94', '11.81', '5.04', '85.23', '33.11', '37.23', '5.49', '31.29', '101.25', '43.15', '96.93', '32.22', '57.8', '107.65', '5.69', '18.74', '58.1', '2.82', '40.48', '32.25', '25.8', '74.33', '45.28', '6.26', '339.62', '116.41', '54.5', '160.2', '275.54', '117.91', '190.99', '75.9', '38.9', '236.03', '17.73', '29.58', '265', '75.8', '12.37', '81.7', '77.64', '144.18', '171.3', '15.99', '67.2', '83.6', '71.3', '65

In [302]:
df['result'] = df['result'].astype('float64')
alamda = df[(df['parameter']=='Oil and Grease')]
alamda
# df.head()

<ipython-input-302-47e689926a4a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['result'] = df['result'].astype('float64')

,station_type,latitude,longitude,county_name,parameter,result,units
11639,Surface Water,37.79690,-121.5852,Alameda,Oil and Grease,1.0,mg/L
484243,Surface Water,38.01850,-121.8150,Contra Costa,Oil and Grease,7.0,mg/L
484269,Surface Water,38.01850,-121.8150,Contra Costa,Oil and Grease,2.0,mg/L
525337,Surface Water,38.02762,-122.1405,Contra Costa,Oil and Grease,4.0,mg/L
639694,Surface Water,36.78660,-120.3854,Fresno,Oil and Grease,1.0,mg/L
...,...,...,...,...,...,...,...
4509531,Surface Water,38.59910,-121.5408,Yolo,Oil and Grease,11.0,mg/L
4509561,Surface Water,38.59910,-121.5408,Yolo,Oil and Grease,2.0,mg/L
4510080,Surface Water,38.59910,-121.5408,Yolo,Oil and Grease,21.0,mg/L
4510164,Surface Water,38.59910,-121.5408,Yolo,Oil and Grease,3.0,mg/L
4510214,Surface Water,38.59910,-121.5408,Yolo,Oil and Grease,4.0,mg/L

In [306]:
# df3 = df.reset_index().groupby(['latitude', 'longitude'])['result'].aggregate('first').unstack()
result = df.groupby(['county_name','parameter']).result.mean()

In [307]:
result = result.reset_index()

In [308]:
count = result.groupby('county_name').size()
data = ['Alameda',
'Colusa',
'Contra Costa',
'Del Norte',
'Fresno',
'Humboldt',
'Los Angeles',
'Merced',
'Placer',
'Sacramento',
'San Joaquin',
'Siskiyou',
'Solano',
'Stanislaus',
'Sutter',
'Trinity',
'Yolo']

In [309]:
result = result[result['county_name'].isin(data)]

In [310]:
param5 = result.reset_index().groupby(['county_name', 'parameter'])['result'].aggregate('first').unstack()

In [311]:
param5

parameter,Chemical Oxygen Demand (COD),Chlorophyll a,Fecal Coliform,Oil and Grease,Total Ammonia,Total Phosphorus,Total Suspended Solids
county_name,,,,,,,
Alameda,NaN,5.918351,NaN,1.000000,0.073812,0.107472,9.895315
Colusa,7.500000,13.994706,NaN,NaN,0.100000,0.107773,38.079944
Contra Costa,23.846154,3.061267,NaN,4.333333,0.101300,0.118157,8.901933
Del Norte,3.000000,1.688182,NaN,NaN,0.025000,0.076385,9.606250
Fresno,8.352174,NaN,NaN,2.400000,0.069375,0.085690,1170.650000
Humboldt,4.722222,1.349512,NaN,NaN,0.024848,0.076642,27.322535
Los Angeles,86.072951,NaN,NaN,16.238434,3.389125,0.075886,84.400000
Merced,28.200524,4.544615,NaN,2.769231,0.079328,0.135718,7.820807
Placer,3.285714,NaN,NaN,2.400000,0.016105,0.020258,2.198864
Sacramento,6.626316,2.226573,NaN,9.750000,0.106949,0.279112,27.079506
San Joaquin,15.552590,14.424186,95458.846154,3.285714,0.244279,0.203199,10.926179
Siskiyou,16.869565,2.752895,NaN,NaN,0.137593,0.158798,6.403367
Solano,26.000000,3.655259,980.400000,NaN,0.092477,0.166858,21.351509
Stanislaus,25.263057,NaN,NaN,2.380952,0.366308,0.378242,8680.000000
Sutter,7.365812,NaN,NaN,3.230769,0.052000,0.124899,22.605556
Trinity,3.555556,0.762727,NaN,NaN,0.032727,0.034286,1.923077
Yolo,12.357831,12.582367,NaN,6.000000,0.094082,0.309187,45.042263

In [312]:
def cod_idx(x):
    if pd.isna(x):
        return 0**0.11
    elif x <= 3 :
        return 100**0.11
    elif x > 3 and x <= 25 :
        return 67**0.11
    elif x > 25 and x <= 50 :
        return 34**0.11
    else :
        return 1**0.11
def clr_idx(x):
    if pd.isna(x):
        return 0**0.11
    elif x <= 1.4 :
        return 100**0.11
    elif x > 1.3 and x <= 10 :
        return 67**0.11
    elif x > 10 and x <= 20 :
        return 34**0.11
    else :
        return 1**0.11
# def ong_idx(x):
#     if pd.isna(x):
#         return 0**0.18
#     elif x == 0 :
#         return 100**0.18
#     elif x > 0 and x <= 0.2 :
#         return 67**0.18
#     elif x > 0.2 and x <= 0.3 :
#         return 34**0.18
#     else :
#         return 1**0.18
def TN_idx(x):
    if pd.isna(x):
        return 0**0.12
    elif x <= 0.25 :
        return 100**0.12
    elif x > 0.25 and x <= 0.75 :
        return 67**0.12
    elif x > 0.75 and x <= 1.5 :
        return 34**0.12
    else :
        return 1**0.12
# def fcoli_idx(x):
#     if pd.isna(x):
#         return 0**0.09
#     elif x <= 500 :
#         return 100**0.09
#     elif x > 500 and x <= 2000 :
#         return 67**0.09
#     else :
#         return 1**0.09
def TP_idx(x):
    if pd.isna(x):
        return 0**0.12
    elif x <= 0.02 :
        return 100**0.12
    elif x > 0.02 and x <= 0.5 :
        return 67**0.12
    elif x > 0.5 and x <= 1 :
        return 34**0.12
    else :
        return 1**0.12
def TSS_idx(x):
    if pd.isna(x):
        return 0**0.18
    elif x <= 20 :
        return 100**0.18
    elif x > 20 and x <= 100 :
        return 67**0.18
    else :
        return 1**0.18

In [257]:
test = clr_idx(0.1)*TSS_idx(20)*TP_idx(0.02)*fcoli_idx(1)*TN_idx(0.1)*ong_idx(0)*cod_idx(1)
print(test**(1/0.92))

95.11759691218703

In [313]:
clr_column = param5['Chlorophyll a']
new_clr_column = clr_column.apply(clr_idx)
param5['Chlorophyll a'] = new_clr_column
TSS_column = param5['Total Suspended Solids']
new_TSS_column = TSS_column.apply(TSS_idx)
param5['Total Suspended Solids'] = new_TSS_column
TP_column = param5['Total Phosphorus']
new_TP_column = TP_column.apply(TP_idx)
param5['Total Phosphorus'] = new_TP_column
# fcoli_column = param5['Fecal Coliform']
# new_fcoli_column = fcoli_column.apply(fcoli_idx)
# param5['Fecal Coliform'] = new_fcoli_column
# ong_column = param5['Oil and Grease']
# new_ong_column = ong_column.apply(ong_idx)
# param5['Oil and Grease'] = new_ong_column
TN_column = param5['Total Ammonia']
new_TN_column = TN_column.apply(TN_idx)
param5['Total Ammonia'] = new_TN_column

In [314]:
cod_column = param5['Chemical Oxygen Demand (COD)']
new_cod_column = cod_column.apply(cod_idx)
param5['Chemical Oxygen Demand (COD)'] = new_cod_column
param5['Chlorophyll a'] = new_clr_column
param5['Total Suspended Solids']=new_TSS_column
param5['Total Phosphorus'] = new_TP_column
# param5['Fecal Coliform'] = new_fcoli_column
# param5['Oil and Grease'] = new_ong_column
param5['Total Ammonia'] = new_TN_column
param5

parameter,Chemical Oxygen Demand (COD),Chlorophyll a,Fecal Coliform,Oil and Grease,Total Ammonia,Total Phosphorus,Total Suspended Solids
county_name,,,,,,,
Alameda,0.000000,1.588065,NaN,1.000000,1.737801,1.656262,2.290868
Colusa,1.588065,1.473882,NaN,NaN,1.737801,1.656262,2.131540
Contra Costa,1.588065,1.588065,NaN,4.333333,1.737801,1.656262,2.290868
Del Norte,1.659587,1.588065,NaN,NaN,1.737801,1.656262,2.290868
Fresno,1.588065,0.000000,NaN,2.400000,1.737801,1.656262,1.000000
Humboldt,1.588065,1.659587,NaN,NaN,1.737801,1.656262,2.131540
Los Angeles,1.000000,0.000000,NaN,16.238434,1.000000,1.656262,2.131540
Merced,1.473882,1.588065,NaN,2.769231,1.737801,1.656262,2.290868
Placer,1.588065,0.000000,NaN,2.400000,1.737801,1.656262,2.290868
Sacramento,1.588065,1.588065,NaN,9.750000,1.737801,1.656262,2.131540
San Joaquin,1.588065,1.473882,95458.846154,3.285714,1.737801,1.656262,2.290868
Siskiyou,1.588065,1.588065,NaN,NaN,1.737801,1.656262,2.290868
Solano,1.473882,1.588065,980.400000,NaN,1.737801,1.656262,2.131540
Stanislaus,1.473882,0.000000,NaN,2.380952,1.656262,1.656262,1.000000
Sutter,1.588065,0.000000,NaN,3.230769,1.737801,1.656262,2.131540
Trinity,1.588065,1.659587,NaN,NaN,1.737801,1.656262,2.290868
Yolo,1.588065,1.473882,NaN,6.000000,1.737801,1.656262,2.131540

In [268]:
acumulate = 1
for n in param5.iloc[10]:
    acumulate = acumulate * n
print(acumulate**1.08695652174)

20.539961602552214

In [315]:
param5 = param5.drop(['Fecal Coliform','Oil and Grease'], axis=1)
param5

parameter,Chemical Oxygen Demand (COD),Chlorophyll a,Total Ammonia,Total Phosphorus,Total Suspended Solids
county_name,,,,,
Alameda,0.000000,1.588065,1.737801,1.656262,2.290868
Colusa,1.588065,1.473882,1.737801,1.656262,2.131540
Contra Costa,1.588065,1.588065,1.737801,1.656262,2.290868
Del Norte,1.659587,1.588065,1.737801,1.656262,2.290868
Fresno,1.588065,0.000000,1.737801,1.656262,1.000000
Humboldt,1.588065,1.659587,1.737801,1.656262,2.131540
Los Angeles,1.000000,0.000000,1.000000,1.656262,2.131540
Merced,1.473882,1.588065,1.737801,1.656262,2.290868
Placer,1.588065,0.000000,1.737801,1.656262,2.290868
Sacramento,1.588065,1.588065,1.737801,1.656262,2.131540
San Joaquin,1.588065,1.473882,1.737801,1.656262,2.290868
Siskiyou,1.588065,1.588065,1.737801,1.656262,2.290868
Solano,1.473882,1.588065,1.737801,1.656262,2.131540
Stanislaus,1.473882,0.000000,1.656262,1.656262,1.000000
Sutter,1.588065,0.000000,1.737801,1.656262,2.131540
Trinity,1.588065,1.659587,1.737801,1.656262,2.290868
Yolo,1.588065,1.473882,1.737801,1.656262,2.131540